### ISSUE TITLE
Support $(ExecutablePath) in PATH extension for test discovery and execution

### ISSUE THREAD

**Issue by jenshemprich** [csoltenborn/GoogleTestAdapter#255] opened 2019-01-11 16:41 UTC
Avoid hard-coded paths or copies of external binaries by evaluating $(ExecutablePath) in PATH extension for test discoveries and executions.
 
The locations of external binaries can be set in Project->Properties->VC-Directories->Executable Directories and are applied when debugging. But GTA ignores any definitions made in the project property pages and neither discovers or executes related tests. NUnit at least discovers the tests, but also fails to executes them.

Benefits of the proposed feature:

If the solution contains multiple projects and configurations (I have to maintain Debug, Release-AVX, Release-AVX2, some CUDA configs), maintaining the references the external binaries becomes much simpler. Just define the executable path configuration-aware in a MSBuild targets/props file (or the project xml) and concatenate it to the existing $(ExecutablePath). For instance:
```
 <PropertyGroup>
    <_PropertySheetDisplayName>TensorFlow</_PropertySheetDisplayName>
    <VC_VERSION>vc15</TENSORFLOW_DIR>
    <LIB_DIR>c:\Developer\</TENSORFLOW_DIR>
    <TENSORFLOW_DIR>$(LIB_DIR)tensorflow\r1.10\</TENSORFLOW_DIR>
    <ExecutablePath>$(TENSORFLOW_DIR)$(VC_VERSION)\$(Configuration)\bin\;$(ExecutablePath)</ExecutablePath>
  </PropertyGroup>
```

would evaluate (depending on the selected project configuration) on my system to
`F:\Developer\lib\tensorflow\r1.10\vc15\Debug\bin\`
or
`F:\Developer\lib\tensorflow\r1.10\vc15\Release-cuda-avx2\bin\`

This way it's relatively easy to maintain multiple build configurations with a single definition, and to discover & run tests without having to copy external binaries into the $(TargetDir).

When dealing with multiple projects, these definitions can also be placed in external MSBuild props (or Targets), which are then referenced by all the projects in the solution. Example code: https://github.com/jenshemprich/lib

**Comment by csoltenborn** [comment] 2019-01-14 12:47
Thanks for your feature request! If I understand you correctly, you'd like to re-use existng VS configuration (which currently has to additionally be provided through GTA's own settings), in particular `ExecutablePath`.

This appears to be a duplicate of #175 - thus, if you do not mind, I will close this issue and reference it from #175. Feel free to object...

**Closed** 2019-01-14 12:48 UTC
Labels: duplicate, enhancement

**Comment by jenshemprich** [comment] 2019-01-16 11:01
Yes, that's good for me. Thank you.
