### ISSUE TITLE
Issue : GoogleTestAdapter dependency on VS core binaries

### ISSUE THREAD

**Issue by singhsarab** [csoltenborn/GoogleTestAdapter#167] opened 2017-09-19 12:45 UTC
Assembly Name : GoogleTestAdapter.TestAdapter 
Version: 0.10.2.874

Issue : Adapter depends on Microsoft.VisualStudio.Shell.11.0

Expectation :
Adapter assembly containing the implementation for ITestDiscoverer and ITestExecutor should not depend on the core VS assemblies like Microsoft.VisualStudio.Shell.11.0. 
All the code required for running tests via TestExplorer, which brings in VS core related dependency should go in a separate assembly.

Reasoning :
Moving forward TestPlatform component that actually loads the adapter to run the tests, will be portable and would be independent of Visual Studio. It would not search in VS locations to find VS related dependencies.
The idea is that users should be able to run the tests using the test runner without any VS installation.

**Comment by csoltenborn** [comment] 2017-09-20 06:24
Thanks for your feature request! Couple of thoughts:
* The `Core` project contains the main logic and does not have any dependencies on VS dlls already
* The `TestAdapter` project realizes the actual integration into VS - I'm thus not sure whether removing those dependencies is in fact worth the effort (a non-VS version of GTA would not have to make use of the `ITestDiscoverer` and `ITestExecutor` interfaces at all imho)
* I must admit that I do not have resources for this in the coming month

Thus, my suggestion is to wait until I have finally managed to merge the MS contributions into GTA's repository (see branch #154 for a preview), which will change the solution structure quite a bit. If this is done, I would be happy to discuss the needed changes in more detail, but would have to rely on (e.g.) your work for realizing this...

**Comment by csoltenborn** [comment] 2017-10-06 19:04
I have thought again about your suggestion and figured that I'd like to close this issue. The rational is that a VS independent version of GTA would rely on the `Core` project - `TestAdapter` only does VS integration. Feel free to re-open if you do not agree.

In case you plan to indeed re-use GTA, but run into problems caused by such dependencies, let me know.

**Closed by csoltenborn** 2017-10-06 19:04 UTC
Labels: wontfix

**Comment by singhsarab** [comment] 2017-10-09 06:36
There are 2 main components when we talk about integration with VS
1. TestExplorer (or TestWindow) : This is component is loaded inside the VS and is responsible for finding the test projects, reading the runsettings, showing the tests.
2. TestPlatform : This a separate component that is responsible for actual discovery/run of the tests.

It is important that we separate out the responsibilities while we write adapters/extensions.
1. ITestContainerDiscoverer or IRunSettingsService implementations are specific to TestWindow. Assembly containing implementations for these interfaces may have VS dependencies.

2. ITestDiscoverer and ITestExecutor : These are required by the TestPlatform. TestPlatform is independent of VS. Hence *TestAdapter.dll assembly that should have these implementations should not have the any dependency on VS.
This also enables you to run the tests using the TestPlatform console runner.
