### ISSUE TITLE
GTA stops after some tests

### ISSUE THREAD

**Issue by arator68** [csoltenborn/GoogleTestAdapter#326] opened 2021-05-31 10:36 UTC
GTA version 0.18.0.1432

GTA stops working after some test.

My UnitTest.exe has round about 7000 Test (5000 with name __UNITTEST__. When i call it via vsTest.Console i use the following parameter: 

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\TestPlatform\vstest.console" r:\bin\unittesting.exe /Settings:"c:\temp\unittesting.gta.runsettings" /logger:trx;LogFileName="result.trx"   /TestCaseFilter:FullyQualifiedName~__UNITTEST__

Runsettings:
<?xml version="1.0" encoding="utf-8"?>

<RunSettings>
  
  <RunConfiguration>
    <ResultsDirectory>c:\temp\TestResults</ResultsDirectory>
    <TargetPlatform>x86</TargetPlatform>
    <MaxCpuCount>0</MaxCpuCount>
	<TestAdaptersPaths>\packages\GoogleTestAdapter.0.18.0\build\_common</TestAdaptersPaths>	
  </RunConfiguration>
 
  
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="trx" enabled="True">
        <Configuration>
          <LogFileName>result.trx</LogFileName>
        </Configuration>
  </LoggerRunSettings>
 
  
  
  
  <GoogleTestAdapterSettings>
		<ProjectSettings>
			<Settings ProjectRegex="r:\\bin\\unittesting\.exe">
				<ShuffleTestsSeed>4</ShuffleTestsSeed>
			</Settings>
		</ProjectSettings>
  
  </GoogleTestAdapterSettings>
 
  </RunSettings>

Problem: Testrun never ends

**Comment by csoltenborn** [comment] 2021-06-02 16:10
This is probably not related to GTA, but to your tests. First try to run them on the console without VsTest.Console.exe and see whether that invocation behaves differently.

**Comment by arator68** [comment] 2021-06-03 05:20
Works fine without VSTest.Console.exe. All tests are passed

**Comment by csoltenborn** [comment] 2021-06-03 09:31
Then I need more information (settings, log output etc). What happens if the tests are run from inside Visual Studio?

**Comment by csoltenborn** [comment] 2021-06-08 06:36
Any news on this one? As I said, I will need much more information if I shall try to help...

**Comment by arator68** [comment] 2021-06-11 09:31
hi and sorry for the delay.

[Log1.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/6637352/Log1.txt)
[Log2.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/6637353/Log2.txt)

i hope this is what you need

**Comment by csoltenborn** [comment] 2021-06-11 16:46
Ok, this shows that everything appears to be working fine in Visual Studio (this is the output of the VS Test output window, right?)

First, make sure that this command, executed on the console, works as desired - it should result in the same output as in Log2.txt (except beginning and end):

```
r:\bin\UnitTesting.exe --gtest_output="xml:C:\MyTemp\MyTemp\tmpC4B2.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=0 --unattended --gtest_filter=*__UNITTEST__*
```

If this is the case, please post your file `c:\temp\unittesting.gta.runsettings`, the `result.trx` file as well as any output `VsTestConsole.exe` produces with your above call.

As a side note: You are using different filtering mechanisms: `--gtest_filter` within VS, `TestCaseFilter` (and whatever is contained in your runsettings file) for `VsTestConsole.exe`.

**Comment by arator68** [comment] 2021-06-14 07:21
Hi, here some additional infos 

vstest.console calls unittesting.exe with this parameter
"r:\bin\unittesting.exe" --gtest_output="xml:C:\MyTemp\MyTemp\tmpCB42.tmp" --gtest_catch_exceptions=1 --gtest_break_on_failure=0 --gtest_filter=__UNITTEST__CachingUnitTest.*:__UNITTEST__ComosArrayObjectTest.*:__UNITTEST__D3ObjectTests.*:__UNITTEST__DeletingDatabaseTables.*:__UNITTEST__NumberOfCreatedObjectsPure.*:__UNITTEST__NumberOfCreatedObjectsTests.*:__UNITTEST__DelayedHierarchyUpdaterTests.*:__UNITTEST__GetCDeviceBySystemFullNameTests.*:__UNITTEST__CPLTObjectCollectionTests.*:__UNITTEST__CPLTTimestampTests.*:__UNITTEST__SoftDeletionUnitTests.*:__UNITTEST__Trying_to_change_description_in_workinglayer_display_mode.*:__UNITTEST__GetLinkedSpecificationTests.*:__UNITTEST__ScanCDevicesTest.*:__UNITTEST__ScanDocumentsTest.*:__UNITTEST__SpecificationScannerTests.*:__UNITTEST__ScanDevicesTest.*:__UNITTEST__Trigger.*:__UNITTEST__PastingObjectFromAnotherProject.*:__UNITTEST__ReferenceCountingTests.*:__UNITTEST__TranslatedTextWithDelimiterTests.*:__UNITTEST__IndexDefinition.*:__UNITTEST__TableImplementationTests.*:__UNITTEST__FreePropertyModificationTests.*:__UNITTEST__WithPreservedClipboardObjectTests.*:__UNITTEST__ProviderTests.*:__UNITTEST__ExceptionWithSettingStatusTests.*:__UNITTEST__FakingTranslationsTests.*:__UNITTEST__IteratingOverUsedFreePropertyGroups.*:__UNITTEST__CollectionsMemoryTests.*:__UNITTEST__MEMORY__Collections.*:__UNITTEST__CDeviceDereferentiationTests.*:__UNITTEST__ChangedObjectsCollectionsTests.*:__UNITTEST__ComosUIDValidityTests.*:__UNITTEST__DeviceCollectionsTests.*:__UNITTEST__CreatingInteractiveReport.*:__UNITTEST__DocumentTypeTests.*:__UNITTEST__CreateElementTests.*:__UNITTEST__ElementGroupsDbVersionTests.*:__UNITTEST__ElementGroupsTests.*:__UNITTEST__ElementGroupsInfoTests.*:__UNITTEST__ElementCountTests.*:__UNITTEST__ElementTreeTraversalEndlessLoopTests.*:__UNITTEST__ElementTreeTraversalTests.*:__UNITTEST__GetInheritParent.*:__UNITTEST__OverlayIdTests.*:__UNITTEST__PathFullNameTests.*:__UNITTEST__UndoStateTests.*:__UNITTEST__WorksetTerminateTests.*:__UNITTEST__XObjTests.*:__UNITTEST__ClassIdTest.*:__UNITTEST__CleanerForexternalCallTest.*:__UNITTEST__CPLTCollectionTests.*:__UNITTEST__LanguageSelectorImplementationTests.*:__UNITTEST__ShadowCollectionTests.*:__UNITTEST__LayerTests.*:__UNITTEST__RightsForCollectionsTests.*:__UNITTEST__DeriveBaseHolderTest.*:__UNITTEST__GetSpecificationByNameTests.*:__UNITTEST__HelpTextOfSpecsTests.*:__UNITTEST__InheritanceTests.*:__UNITTEST__SiValueTests.*:__UNITTEST__XValuesTests.*:__UNITTEST__StandardValueTests.*:__UNITTEST__SystemTypeTests.*:__UNITTEST__TempCollectionTests.*:__UNITTEST__WorksetDependentTempCollectionTests.*:__UNITTEST__UndoStateHandlingTests.*:__UNITTEST__WithProgressBarTests.*:__UNITTEST__CurrentProject.*:__UNITTEST__ProjectContextTests.*:__UNITTEST__CPLTXDataWrapperTest.*:__UNITTEST__CreationTimestampTests.*:__UNITTEST__SecurityUnionTests.*:__UNITTEST__InWorkingLayerDisplayMode.*:__UNITTEST__RightsSimulationTests.*:__UNITTEST__SpecificationSetRightsTests.*:__UNITTEST__SettingDocumentVersion.*:__UNITTEST__RevisionsBasedOnModificationOfDataSource_ProjectOptionTests.*:__UNITTEST__ScriptResultCacheTests.*:__UNITTEST__ScriptStackTests.*:__UNITTEST__SearchConditionTest.*:__UNITTEST__SearchManagerTest.*:__UNITTEST__SearchManagerValidationTest.*:__UNITTEST__SessionIdRangeTests.*:__UNITTEST__SessionIdSelectionTests.*:__UNITTEST__LicenseTests.*:__UNITTEST__XmlSpecificationTests.*:__UNITTEST__IteratingOverLoadedSpecifications.*:__UNITTEST__NumberRangeGeneratorTests.*:__UNITTEST__NrgNameAndLabelAdjustmentTests.*:__UNITTEST__Given_an_overlay_release_in_a_sql_database.*:__UNITTEST__A_new_free_property.*:__UNITTEST__VbScriptEngineTests.*:__UNITTEST__FindingSpecificationsByFreePropertyTests.*:__UNITTEST__SetOwnLinkObjectTest.*:__UNITTEST__MEMORY__GetMemoryUsageTests.*:__UNITTEST__RollbackTests.*:__UNITTEST__BackCollectionIdTests.*:__UNITTEST__BackCollectionTests.*:__UNITTEST__ResourceToolTests.*:__UNITTEST__DatabaseTests.*:__UNITTEST__ClipboardTests.*:__UNITTEST__PltStringArrayTest.*:__UNITTEST__ComosMapIterationTests.*:__UNITTEST__LoadedExtensionsContainerTests.*:__UNITTEST__ExternalRightsRestrictionTests.*:__UNITTEST__ExternalRightsExtensionPointTests.*:__UNITTEST__RightsRestrictionExceptionTest.*:__UNITTEST__SystemFullNameTest.*:__UNITTEST__ObjectRightsRestrictionTests/0.*:__UNITTEST__ObjectRightsRestrictionTests/1.*:__UNITTEST__ObjectRightsRestrictionTests/2.*:__UNITTEST__ObjectRightsRestrictionTests/3.*:__UNITTEST__ObjectRightsRestrictionTests/4.*:__UNITTEST__ObjectRightsRestrictionTests/5.*:__UNITTEST__ObjectRightsRestrictionTests/6.*:__UNITTEST__ObjectRightsRestrictionTests/7.*:__UNITTEST__ObjectRightsRestrictionTests/8.*:__UNITTEST__ObjectRightsRestrictionTests/9.*:__UNITTEST__ObjectRightsRestrictionTests/10.*:__UNITTEST__ObjectRightsRestrictionTests/11.*:__UNITTEST__ObjectRightsRestrictionTests/12.*:__UNITTEST__ObjectRightsRestrictionTests/13.*:__UNITTEST__ObjectRightsRestrictionTests/14.*:__UNITTEST__ObjectRightsRestrictionTests/15.*:__UNITTEST__LinkInfoTests.*:__UNITTEST__LinkInfoOnSpecificationTests.*:__UNITTEST__StaticLinkInfoOnSpecificationTests.*:__UNITTEST__com_ptr_tests.*:__UNITTEST__UndoStateCheckAndCorrectObjectsTests.*:__UNITTEST__UndoStateUndoTests.*:__UNITTEST__WorksetInitTests.*:__UNITTEST__HierarchicalScannerTest.*:__UNITTEST__CheckObjectPropertiesTests.*:__UNITTEST__LoopDetectorTests.*:__UNITTEST__OverlayPathTests.*:__UNITTEST__SettingBaseOverlayTests.*:__UNITTEST__OverlayOrReleasedAreaTests.*:__UNITTEST__TranslationTests.*:__UNITTEST__ComosUidTests.*:__UNITTEST__UsingDatabaseTransactionTests.*:__UNITTEST__OverlayReleaseAssumptionTests.*:__UNITTEST__Setting_extension_on_a_filename.*:__UNITTEST__Combining_folder_path.*:__UNITTEST__Extracting_drive_letter.*:__UNITTEST__LoginTestForInvalidUserCredentials.*:__UNITTEST__FileNameCalculatorTests.*:__UNITTEST__ObjectStructureUnitTests.*:__UNITTEST__BaseObjectPointerTest.*:__UNITTEST__ObjectTestTests.*:__UNITTEST__ProjectTests.*:__UNITTEST__ResettingRevisionsTests.*:__UNITTEST__AfterPasteScriptsTests.*:__UNITTEST__BeforePasteScriptsTests.*:__UNITTEST__CanBeCopiedScriptTests.*:__UNITTEST__CanBeCutScriptTests.*:__UNITTEST__ScriptingTests.*:__UNITTEST__SessionTimestampTests.*:__UNITTEST__TimestampTests.*:__UNITTEST__DepthFirstSearchTest.*:__UNITTEST__ReachableNodesTest.*:__UNITTEST__PhysUnitTests.*:__UNITTEST__ComosUIDTests.*:__UNITTEST__VarstorageTest.*:__UNITTEST__ConnectorTests.*:__UNITTEST__ComosMapTest.*:__UNITTEST__CharEscapingTest.*:__UNITTEST__ConvertPatternTest.*:__UNITTEST__DatabaseVersionChangeTests.*:__UNITTEST__WithTempFolderTests.*:__UNITTEST__RollbackStateItemTest.*:__UNITTEST__AdminRightsTest.*:__UNITTEST__GetInternationalDisplayValueTest.*:__UNITTEST__ComosLibraryTest.*:__UNITTEST__LiteralCharacterConversionTests.*:__UNITTEST__StringToLongTests.*:__UNITTEST__VariantToStringTest.*:__UNITTEST__VariantToDoubleTest.*:__UNITTEST__VariantToIntTest.*:__UNITTEST__VariantToLongLongTest.*:__UNITTEST__CopyableUniquePointerTests.*:__UNITTEST__ExecutionProgressVisualizerTests.*:__UNITTEST__FinallyTests.*:__UNITTEST__Showing_message_boxes_through_GlobalFunctions.*:__UNITTEST__MultiThreadingToolForMainThreadTests.*:__UNITTEST__OverlayLoginTest.*:__UNITTEST__SimpleListItemTest.*:__UNITTEST__StringSerializableArrayTests.*:__UNITTEST__SplitStringTest.*:__UNITTEST__ContainsCIWithLocaleTests.*:__UNITTEST__StringToolsTests.*:__UNITTEST__VectorToolsTests.*:__UNITTEST__WithTemporaryValueTests.*:__UNITTEST__CopyContentsWithOwnerChainTests.*:__UNITTEST__HeartbeatTest.*:__UNITTEST__NumericLibTest.*:__UNITTEST__A_new_workset.*:__UNITTEST__Setting_a_message_box_handler.*:__UNITTEST__Undoing_all_via_workset.*:__UNITTEST__After_workset_is_terminated.*:__UNITTEST__During_workset_termination.*:__UNITTEST__After_workset_termination.*:__UNITTEST__CallStackTests.*:DisplayValueAndNumericValuesTestCases/__UNITTEST__DisplayValueAndNumericValuesTest.*:DistanceScenarios/__UNITTEST__DistanceCalculatorTests.*:TestCases/__UNITTEST__SystemTypeOwnerRelations.*:LoadedNotChanged_IS_releasable/__UNITTEST__CanBeReleasedFromCacheTest.*:Changed_is_NOT_releasable/__UNITTEST__CanBeReleasedFromCacheTest.*:CreatedThenDeleted_IS_releasable/__UNITTEST__CanBeReleasedFromCacheTest.*:LoadedThenDeleted_is_NOT_releasable/__UNITTEST__CanBeReleasedFromCacheTest.*:

This is the generatet tempfile

[tmpCB42.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/6646310/tmpCB42.txt)

This is the runnsettings file that i used

[unittesting.gta.runsettings.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/6646318/unittesting.gta.runsettings.txt)

it stops at the last test

**Comment by csoltenborn** [comment] 2021-06-22 09:55
I don't see any obvious issues. Since the tempfile appears to be complete (these is the closing `testsuites` tag), my guess would be that this is not an issue of GTA, but of `vstest.console.exe` itself. My suggestion would be to have a try with the MS flavor of GTA, and if this has the same problem, to contact MS about it (and in case that it works with TAfGT, please let me know)...

**Comment by arator68** [comment] 2021-06-25 06:47
When i use the GTA from Microsoft, it works.
With the GTA Adapter from here (get with nuget) it not works

**Comment by csoltenborn** [comment] 2021-06-25 08:04
That's interesting - thanks for letting me know... 

However, the only thing I can offer to you is that you run the *exact same* command with GTA and TAfGT, and then provide all resulting artefacts (logs, output, result files) - maybe I can then see what's the difference...

The only alternative would be to provide your solution (or test executables, config files etc.) such that I can try to reproduce the issue locally.

**Comment by csoltenborn** [comment] 2021-07-13 14:39
Closed due to inactivity - feel free to reopen...

**Closed by csoltenborn** 2021-07-13 14:39 UTC
