### ISSUE TITLE
"Debug selected test" loads bunch of .dlls that are not loaded when hitting F5 directly.

### ISSUE THREAD

**Issue by Knitschi** [csoltenborn/GoogleTestAdapter#152] opened 2017-07-20 09:06 UTC
Hi GoogleTestAdapter devs!

First of all, thank you for your work on this project.
Now my problem...
When I start my test executable by setting it as startup project and hitting F5, it starts almost instantly.
However when I try to debug a testcase by clicking the "Debug Selected Test" option in the Test Explorer, I get a popup window that shows me how Visual Studio loads all kinds of dlls, which are probably not even needed to debug my test. Because of this startig to debug a test takes about 20 seconds which is a little long for a quick test-driven development cycle.

I am not sure if this is a problem of the Google Test Adabter or of Visual Studio itself. 
Do you know the problem and a way to solve it?

Thank you for your time.

Edit: Maybe I should mention that I work with VS2015. I have not tried if the problem exists on VS2017

**Comment by csoltenborn** [comment] 2017-07-20 18:03
Thanks for the kudos and your bug report! We have [heard of this before](https://marketplace.visualstudio.com/items?itemName=ChristianSoltenborn.GoogleTestAdapter) (see 4th comment), but are not sure about the cause. However, the good news is that we are [collaborating with MS](https://blogs.msdn.microsoft.com/vcblog/2017/05/10/unit-testing-and-the-future-announcing-the-test-adapter-for-google-test/) since a couple of months; we are currently in the process of synchronizing our repositories, but will probably address this in the not too far future. Stay tuned...

**Comment by Knitschi** [comment] 2017-07-24 08:30
Thanks. This sounds great :-)

**Comment by gobater** [comment] 2018-01-22 18:04
Hi,

Any news on this topic? I am facing the same issue with VS2015 and it is quite annoying since it slow downs debugging/fixing failing Unittests

Let me know If there is any way to support you (by means of logs, ...)

Regards

**Comment by csoltenborn** [comment] 2018-01-22 18:10
No, not yet. I'm currently busy with other stuff, but will come back to this in a couple of weeks (I hope)...

**Comment by hacst** [comment] 2018-03-09 21:42
Any updates? Anything specific blocking this we can help with?

GTA is great and this issue is the one that impacts my current workflow with it the most. I still regularily find myself running the test exe as a startup project with a manually configured filter string because it just takes so long to get into the actual debugging when launching it by using "Debug selected test" from GTA.

**Comment by csoltenborn** [comment] 2018-03-10 09:16
That's indeed a pity... To be honest, I do not have a lot of knowledge in that area (and no time to look into it on that base), and I kind of hope that MS will at some point in time tackle this issue. Of course, a pull request fixing this issue would be more than welcomed - if you want to give it a shot, I will gladly provide help!

**Comment by aey76** [comment] 2018-08-27 15:35
It seems that this problems does not exist in vs 2017 version 15.8.0.

**Comment by csoltenborn** [comment] 2018-08-27 17:02
That would be quite awesome :-) 

I will give it a try in the next days - please let me know in case your experience changes.

**Comment by csoltenborn** [comment] 2018-12-09 09:37
Closed because the problem seems to have been resolved by a VS update.

**Closed by csoltenborn** 2018-12-09 09:37 UTC
Labels: bug
