### ISSUE TITLE
Exception in LogSafe() while running tests (Version 0.10.0)

### ISSUE THREAD

**Issue by jhill84** [csoltenborn/GoogleTestAdapter#141] opened 2017-05-08 10:12 UTC
Since switching to version 0.10.0 I occasionally get an IndexOutOfRangeException when executing tests.

This is what the error log says:

2017-05-05T09:29:16.0708446Z ##[error]Fehler: ERROR: Exception while running tests: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
2017-05-05T09:29:16.0708446Z ##[error]   bei System.Collections.Generic.List'1.Add(T item)
2017-05-05T09:29:16.0708446Z ##[error]   bei GoogleTestAdapter.TestAdapter.Framework.VsTestFrameworkLogger.LogSafe(TestMessageLevel level, String message)
2017-05-05T09:29:16.0708446Z ##[error]   bei GoogleTestAdapter.TestAdapter.Framework.VsTestFrameworkLogger.Log(Severity severity, String message)
2017-05-05T09:29:16.0708446Z ##[error]   bei GoogleTestAdapter.Common.LoggerBase.LogInfo(String message)
2017-05-05T09:29:16.0708446Z ##[error]   bei GoogleTestAdapter.Common.LoggerBase.DebugInfo(String message)
2017-05-05T09:29:16.0708446Z ##[error]   bei GoogleTestAdapter.Settings.SettingsWrapper.ExecuteWithSettingsForExecutable(String executable, Action action, ILogger logger)
2017-05-05T09:29:16.0708446Z ##[error]   bei GoogleTestAdapter.TestAdapter.TestExecutor.AddTestCasesOfExecutable(List'1 allTestCasesInExecutables, String executable, SettingsWrapper settings, ILogger logger, Func`1 testrunIsCanceled)
2017-05-05T09:29:16.0708446Z ##[error]   bei GoogleTestAdapter.TestAdapter.TestExecutor.<>c__DisplayClass17_1.<GetAllTestCasesInExecutables>b__2()
2017-05-05T09:29:16.0708446Z ##[error]   bei System.Threading.Tasks.Task.InnerInvoke()
2017-05-05T09:29:16.0708446Z ##[error]   bei System.Threading.Tasks.Task.Execute()
2017-05-05T09:29:16.0708446Z ##[error]   --- Ende der internen Ausnahmestapelüberwachung ---

**Comment by csoltenborn** [comment] 2017-05-08 18:58
Thanks for your report! That bug was caused by a tiny little bit too much of performance optimizations :-)

If you want, you can give [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.10.0.781/job/g5j1r5cb6duj7ayk/artifacts) a try in which the bug should be fixed. The fix will probably be released within this week.

**Closed by csoltenborn** 2017-05-08 18:58 UTC
Labels: bug
