### ISSUE TITLE
Missing test and loads of errors after upgrading to 0.13.0

### ISSUE THREAD

**Issue by lyn444** [csoltenborn/GoogleTestAdapter#227] opened 2018-06-26 08:24 UTC
After updating to the latest verion 0.13.0, there are tests missing from the list and also a bunch of new errors saying could not find source location for all the tests.

![image](https://user-images.githubusercontent.com/2337363/41898733-52ea58c2-795d-11e8-9e5e-64aa68878c01.png)

Any ideas what is happening and what information do I need to provide?

Had to downgrade to 0.12.3.994 which works fine.

Visual Studio Version 2015 Update 3, (14.0.25431.01)
Windows 8.1

**Comment by csoltenborn** [comment] 2018-06-26 08:33
No idea from that screenshot... I assume that you have checked out the [trouble shooting guide](https://github.com/csoltenborn/GoogleTestAdapter#no-source-locations-and-traits-are-found-for-my-tests). 

Please enable debug mode and attach the resulting output as a text file, maybe this helps.

**Comment by lyn444** [comment] 2018-06-26 08:36
feels like it is a path issue of the new update. since 0.12.3 worked perfectly fine.
i ll attach the output.

**Comment by lyn444** [comment] 2018-06-26 08:43
[TestOutput.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/2136299/TestOutput.txt)

![image](https://user-images.githubusercontent.com/2337363/41899826-f987e044-795f-11e8-9a84-8bc6c5caa8cd.png)

Note that there are exceptions on path: The path is not a legal form.

**Comment by lyn444** [comment] 2018-06-26 08:50
This is the screenshot for 0.12.3 which worked fine
![image](https://user-images.githubusercontent.com/2337363/41900290-f757fede-7960-11e8-9fd7-385411f744f2.png)

**Comment by csoltenborn** [comment] 2018-06-26 09:01
I don't see anything obvious, but then, you have apparently forgotten to enable debug mode. I'd like to see what settings are in place, and how the test executables are actually invoked.

As a side note: There's a bug with the *Working directory* option which has already been fixed - would you mind to give [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.13.0.1103/artifacts) a try?

**Comment by lyn444** [comment] 2018-06-26 09:14
[DebugTestOutput.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/2136461/DebugTestOutput.txt)

Oops. OK i have attached the debug mode output.
This output is generated using the above version 0.13.0.1103 but still the problem persists

**Comment by csoltenborn** [comment] 2018-06-26 09:37
Thanks! There is an embarassing bug in the error logging :-) which probably hides your actual problem. Can you please try [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.13.0.1104/artifacts)? Build is currently running, but should be finished in about 15mins...

**Comment by lyn444** [comment] 2018-06-26 10:00
Thanks for your fast response!

OK, here is the debug output for 13.0.1104

[DebugTestOutput0_13_0_1104.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/2136615/DebugTestOutput0_13_0_1104.txt)

Now the exception is gone and it shows new errors:
![image](https://user-images.githubusercontent.com/2337363/41904262-8700286e-796a-11e8-9237-02645d730a83.png)

And indeed the missing tests are from this project.
When doing the test discovery for IntegrationTestAudioEngine from the command line it worked.

![image](https://user-images.githubusercontent.com/2337363/41904342-b7ec3b98-796a-11e8-9b79-e90d7af8fc8b.png)

**Comment by michalfita** [comment] 2018-06-26 10:05
With 1104 I still have these warnings:
```
Warning: Could not find source location for test XXX/YYY
```
But in failed tests at least, I can click on the assert location.

How to enable debug mode?

**Comment by csoltenborn** [comment] 2018-06-26 10:08
@lyn444 Thanks, will have a look later on...

@michalfita Options -> Google Test Adapter -> *Print debug info*

**Comment by csoltenborn** [comment] 2018-06-26 11:43
I have again improved error reporting (this time the actual information is hidden inside an `AggregateException`, which I hope I have treated correctly now). Please check once more with [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.13.0.1105/artifacts) (asa the build is finished)...

**Comment by lyn444** [comment] 2018-06-26 12:37
Thanks. I will get back to this soon and let you know.

**Comment by michalfita** [comment] 2018-06-26 13:10
@lyn444 Thanks. With that enabled, I don't see any errors. However, warnings are still present.

----

Later today: No tests found to run. Nothing in debug...

**Comment by csoltenborn** [comment] 2018-06-26 14:08
@michalfita Have you checked out the trouble shooting guide? If you haven't, please start with that. Otherwise (or if it does not help), please open an own issue for your problem, since it doesn't look directly related to the one of @lyn444 (he's got errors, you've ot warnings :-) )...

**Comment by lyn444** [comment] 2018-06-26 15:12
@csoltenborn 
Actually i think it is related since here i also got the same warnings.

So the original post actually stated two problems from me:
1. the "Warning: Could not find source location for test"
2. The missing test from integrationtestaudioengine

**Comment by lyn444** [comment] 2018-06-26 15:20
[DebugTestOutput0_13_0_1105.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/2137752/DebugTestOutput0_13_0_1105.txt)


OK, i have uploaded the output for 0.13.1105
Apprently it complained about illegal characters in path
![image](https://user-images.githubusercontent.com/2337363/41922348-753686f0-7997-11e8-8cbf-6d7a24bb674d.png)


ive no idea why the path contains illegal characters.

**Comment by lyn444** [comment] 2018-06-26 15:20
And the warning  Could not find source location for test" still exists

**Comment by csoltenborn** [comment] 2018-06-26 17:01
Thanks for the info! We're getting to it...

GTA searches for a binary's PDB partly by looking into the directories provided by the system's `PATH` variable, and that crashes. I thus think that you have something weird on your system's `PATH`. The [version I just created](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.13.0.1106/artifacts) catches that exception, ignores the according path element, and tells you about it.

The "Could not find source location" warnings are most likely caused by this, since GTA gets the source locations from the PDB file (and crashes while trying to do that). Let's see if GTA will now be able to find your PDB - if it can't, it will tell you where it looked for it.

In fact, I would have assumed that this is not related to the new GTA version - are you sure that it indeed works with 0.12.3?

**Comment by lyn444** [comment] 2018-06-26 17:17
All right. It is becoming interesting now.
Regarding the version, I'm very sure that 0.12.3 worked well without any problems so maybe there are some other factors in the new version that affected this.

I will give it a go with 1106 tomorrow morning to see what we can find.
Will update you then. Thanks!

**Comment by lyn444** [comment] 2018-06-26 17:33
OK never mind, let us address this issue now. downloading... give me a second to run it.

**Comment by lyn444** [comment] 2018-06-26 17:40
[DebugTestOutput0_13_0_1106.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/2138261/DebugTestOutput0_13_0_1106.txt)

Great! Ok, it is indeed the path issue. someone put a pair of extra quotes in the path. now it finds the tests correctly.

I see why only that test project got this issue since that project import an third party lib that GTA tried to parse.

So i guess that issue is resolved. (still not sure why 0.12.3 worked though)

However the warning is still there so i still cannot double click the test case to navigate to the source file.

**Comment by lyn444** [comment] 2018-06-26 17:47
anyway it is 2am here. hope this helped and will follow up tmr.

**Comment by csoltenborn** [comment] 2018-06-27 04:20
Thanks, and sleep well :-)

I fear that I'm out of ideas for now. Thus, I have created [a version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.13.1.1115/artifacts) with enhanced debug output - it will spit out some information in case a test location can not be found. Additionally, I have reverted one change in that area. This will hopefully show us what's going on).

My recommendation would be to unload all test projects except one - this will make it a bit easier to interprete the log output.

In case this doesn't help, I fear that I need a sample solution to reproduce the issue locally.

**Comment by michalfita** [comment] 2018-06-27 09:12
@csoltenborn Is there any why I can send you logs in private? Mine contain informations I'm not allowed to share in public and I don't think anonymised they still would make sense.

Hint:
```
TestCaseLocation not found (old regex found it: True). Test method signatures:
```

**Comment by csoltenborn** [comment] 2018-06-27 11:36
@michalfita Sure, send it to <firstname>.<lastname>@gmail.com.

However, I might already have an idea (send the log anyways, please, because I'm gonna need it to fix the issue, if that's at all possible): Are your gtest tests by any chance organized into namespaces? Questions also goes to @lyn444 ...

**Comment by michalfita** [comment] 2018-06-27 14:45
@csoltenborn Yes, we use namespaces in test projects.

> if that's at all possible

How it's possible the old mechanism works, but new don't?

Logs sent.

**Comment by lyn444** [comment] 2018-06-27 16:17
@csoltenborn 

sorry didn get enough time to test your build today
maybe i can give it a quick try tmr morning.
yes, all the tests go into their corresponding namespaces....

**Comment by csoltenborn** [comment] 2018-06-27 16:54
GTA 0.13.0 contains a fix which makes sure that tests which are prefixes of other tests still get the correct source location (that's why the build I prepared for you guys failed - I removed the fix, which causes the failing test). On the other hand, namespaces for gtest tests are discouraged (forbidden?) afaik (see e.g. [this thread](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/MwPIo2BnVhM) - in fact, gtest apparently even contains code which  makes tests fail under some circumstances if they are contained in namespaces). I'm currently not sure whether I will be able to figure out a regex which will a) ignore namespaces and b) still identify the correct source locations as described above (pull requests welcome!).  If that turns out to be impossible (or too difficult for me :-) ), I will thus go for the prefix stuff.

The obvious workaround for you guys would be to get rid of the namespaces... but stay tuned.

**Comment by lyn444** [comment] 2018-06-27 17:19
Getting rid of the namespace is not practical as there are friend tests that access private members of class. Doing so will requires a complete refactor and i m even not sure if it is possible at all.

The referred thread only mentioned that the TEST_F to be in the same namespace when using the same test case name which makes sense.

It is the first time that i heard we should put tests in global namespace for the gtest. in fact a simple google search only shows the thread you posted and i didn't see other related posts on this.
 
If you see how the macro works for defining friend test i highly doubt tests should be put in global namespace since that would render the macro completely useless.

anyway, i may be wrong but i doubt this is the case....

**Comment by csoltenborn** [comment] 2018-06-28 05:44
Well, the point is that gtest test names must be unique within their respective binaries afaik, and the namespace isn't part the test names. And, btw, if you need to access private members of a class under test, then that's clearly a test smell imho - tests should not know about the internal implementation of a class to reduce test fragility.

However, it was easier than I hoped to adjust the regex accordingly. Please give [this build](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/build/0.13.1.1116/artifacts) a try...

**Comment by lyn444** [comment] 2018-06-28 07:36
great work!
Thanks for the fix. Just tested and worked like a charm. Appreciated all the work! :p

we need to test certain internal flags as there are certain methods which needs to be done in several steps and there is no point exposing such flags. anyway, i think such discussions must be done within a context to make sense and is it beyond the scope of this thread.

**Comment by michalfita** [comment] 2018-06-28 09:35
Works for me either. Thank you.

**Comment by csoltenborn** [comment] 2018-06-29 04:50
Fix is merged into master, will be released probably at the beginning of next week.

**Closed by csoltenborn** 2018-06-29 04:50 UTC
Labels: bug
