### ISSUE TITLE
Test not found in VS2019

### ISSUE THREAD

**Issue by erutovic** [csoltenborn/GoogleTestAdapter#275] opened 2019-04-03 15:32 UTC
Hi,

This is a duplicate of a question in the marketplace . I post also here since I created a simple project to illustrate the issue : [GTAVS2019.zip](https://github.com/csoltenborn/GoogleTestAdapter/files/3039439/GTAVS2019.zip) . 

The project works in VS2017 but not in VS2019 (No tests found to run.)  I tried the regex discovery option and the ".is_google_test" extension without success.

Thanks for your help, I really like this extension!

Regards,
Manu.

**Comment by csoltenborn** [comment] 2019-04-04 04:23
Thanks for the issue! Can you please embed your project into a solution ready to be opened with VS2017/2019, and upload a zip of that solution? I haven't used cmake before...

But please start by uploading the resulting output of GTA on VS2017/2019 (please enable debug mode) - maybe I can already help based on that output.

**Comment by erutovic** [comment] 2019-04-04 14:05
Hi Christian,
Thanks for your answer. I have embedded the project into a solution and ... it works in VS2019 without problem.  The working project is here: 
[GTAVS2019_SLNWORKING.zip](https://github.com/csoltenborn/GoogleTestAdapter/files/3043774/GTAVS2019_SLNWORKING.zip)

I am using the native CMake support in visual studio since my project is multi-platform (Windows + Linux). You can actually open a CMake project without solution file directly with Visual Studio (Open Folder). CMake is supported natively since VS 2017 (https://devblogs.microsoft.com/cppblog/cmake-support-in-visual-studio/) . 

Here is the debug output in VS2017 (Print Debug Info = true): 
```
[2019-04-04 10:03:08 AM Informational] ------ Discover test started ------
[2019-04-04 10:03:14 AM Warning] Could not locate debug symbols for 'C:\Users\manu\Desktop\GTAVS2019\bin\Calc.Test.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
[2019-04-04 10:03:14 AM Informational] 10:03:14.979 - Visual Studio version: VS2017
[2019-04-04 10:03:15 AM Informational] 10:03:15.036 - Test Adapter for Google Test: Test discovery starting...
[2019-04-04 10:03:15 AM Informational] 10:03:15.084 - Solution settings: AdditionalTestExecutionParam: '', BatchForTestSetup: '', BatchForTestTeardown: '', BreakOnFailure: False, CatchExceptions: True, DebugMode: True, KillProcessesOnCancel: True, MaxNrOfThreads: 3, NrOfTestRepetitions: 1, ParallelTestExecution: False, ParseSymbolInformation: True, PathExtension: '', PrintTestOutput: True, RunDisabledTests: False, ShowReleaseNotes: False, ShuffleTests: False, ShuffleTestsSeed: 0, TestDiscoveryRegex: '', TestDiscoveryTimeoutInSeconds: 30, TestNameSeparator: '', TestPropertySettingsContainer: GoogleTestAdapter.TestAdapter.Settings.TestPropertySettingsContainer, TimestampOutput: True, TraitsRegexesAfter: {}, TraitsRegexesBefore: {}, UseNewTestExecutionFramework: True, WorkingDir: '$(ExecutableDir)'
[2019-04-04 10:03:15 AM Informational] 10:03:15.088 - No settings configured for test executable 'C:\Users\manu\Desktop\GTAVS2019\bin\Calc.Test.exe'; running with solution settings: AdditionalTestExecutionParam: '', BatchForTestSetup: '', BatchForTestTeardown: '', BreakOnFailure: False, CatchExceptions: True, DebugMode: True, KillProcessesOnCancel: True, MaxNrOfThreads: 3, NrOfTestRepetitions: 1, ParallelTestExecution: False, ParseSymbolInformation: True, PathExtension: '', PrintTestOutput: True, RunDisabledTests: False, ShowReleaseNotes: False, ShuffleTests: False, ShuffleTestsSeed: 0, TestDiscoveryRegex: '', TestDiscoveryTimeoutInSeconds: 30, TestNameSeparator: '', TestPropertySettingsContainer: GoogleTestAdapter.TestAdapter.Settings.TestPropertySettingsContainer, TimestampOutput: True, TraitsRegexesAfter: {}, TraitsRegexesBefore: {}, UseNewTestExecutionFramework: True, WorkingDir: '$(ExecutableDir)'
[2019-04-04 10:03:15 AM Informational] 10:03:15.115 - Parsing PDB file C:\Users\manu\Desktop\GTAVS2019\bin\Calc.Test.pdb
[2019-04-04 10:03:15 AM Informational] 10:03:15.187 - Found 1 test method symbols and 0 trait symbols in binary C:\Users\manu\Desktop\GTAVS2019\bin\Calc.Test.exe
[2019-04-04 10:03:15 AM Informational] 10:03:15.276 - Added test case 'CalcTest.Addition'
[2019-04-04 10:03:15 AM Informational] 10:03:15.277 - Found 1 tests in executable C:\Users\manu\Desktop\GTAVS2019\bin\Calc.Test.exe
[2019-04-04 10:03:15 AM Informational] 10:03:15.277 - Test discovery completed, overall duration: 00:00:00.3139726
[2019-04-04 10:03:15 AM Informational] ========== Discover test finished: 1 found (0:00:07.3616398) ==========
```

Here is the debug output in VS2019 (Print Debug Info = true): 
`[2019-04-04 10:00:15 AM Informational] No tests found to run.`

Thanks for your support. Let me know if you need anything else.

**Comment by csoltenborn** [comment] 2019-04-04 16:04
In fact, you are using the [Test Adapter for Google Test](https://github.com/Microsoft/TestAdapterForGoogleTest), the MS clone of Google Test Adapter (GTA, this adapter). Please raise an issue on MS' repository...

Having said that, this looks like a VS regression to me, since it appears that the adapter is not called by VS and thus not given the chance to discover any tests. The same would probably happen with GTA, feel free to give it a try and let me know.

**Comment by erutovic** [comment] 2019-04-04 16:44
Oups! Sorry, I thought it was the exact same thing. I just have tried with GTA and the issue is the same. I will raise an issue on MS's repository.

**Comment by csoltenborn** [comment] 2019-04-05 05:11
Ok, let's see what the MS guys have to say... I will close this for now (and reopen it if it turns out that I can indeed do something about it).

**Closed by csoltenborn** 2019-04-05 05:11 UTC
Labels: MS Adapter, Visual Studio regression?

**Comment by erutovic** [comment] 2019-05-07 14:30
Hi,

In case somebody has the same issue, I was able to solve the problem by using the following command in the test project. everything is up and running now !

add_test(NAME TESTPROJECTNAME COMMAND $<TARGET_FILE:TESTPROJECTNAME >)

**Comment by OtisBricker** [comment] 2019-06-10 18:01
I am having similar issues and am trying to get things working. WHne you say you added the above to the test project, I am not sure I follow you. If you could provide a bit more explanation, I would be grateful. Thanks In Advance!
