### ISSUE TITLE
Administrator privileges are needed to run test

### ISSUE THREAD

**Issue by harrynull** [csoltenborn/GoogleTestAdapter#189] opened 2017-12-15 00:28 UTC
If I don't run Visual Studio as administrator, the following error will appear:
```
[12/15/2017 08:26:48 Informational] ------ Load Playlist started ------
[12/15/2017 08:26:48 Informational] ========== Load Playlist finished (0:00:00.0120005) ==========
[12/15/2017 08:26:49 Informational] ------ Discover test started ------
[12/15/2017 08:27:46 Error] Failed to initialize client proxy: could not connect to test process vstest.discoveryengine.x86.exe.
[12/15/2017 08:27:46 Informational] ========== Discover test finished: 0 found (0:00:57.1256508) ==========
```
Visual Studio version: 15.4.5 (Community 2017).

**Comment by csoltenborn** [comment] 2017-12-15 07:04
I have never seen this problem (and neither have my users afaik). Plus, this appears to not be an error reported by GTA, but by VS. Can you run tests with any other test adapter? In particular, does the *Test Adapter for Google Test* (MS clone of GTA) work?

**Comment by harrynull** [comment] 2017-12-15 07:40
Test Adapter for Google Test does not work either.

**Comment by csoltenborn** [comment] 2017-12-15 07:53
Then I would recommend to try a third adapter (because GTA and TAfGT are pretty similar) - if that doesn't work either, I guess you have an issue with your Visual Studio installation...

**Comment by csoltenborn** [comment] 2017-12-16 10:00
Are there any news on this one? I'm tempted to close it since I assume that the problem is on your side...

**Comment by csoltenborn** [comment] 2017-12-20 06:45
Closed due to inactivity - feel free to re-open if the problem remains.

**Closed by csoltenborn** 2017-12-20 06:45 UTC
Labels: invalid

**Comment by harrynull** [comment] 2017-12-20 07:25
Sorry for the late reply. It seems that it truly problem of my side because the Visual Studio Test Platform does not work either. Thanks for your help.

**Comment by csoltenborn** [comment] 2017-12-20 07:50
Ok, thanks for letting me know! 

I just like to keep the open issues as clean as possible...
