### ISSUE TITLE
Test discovery scans twice, failing the second time and taking 5x longer than it should

### ISSUE THREAD

**Issue by loki980** [csoltenborn/GoogleTestAdapter#191] opened 2018-01-17 23:45 UTC
Here's a rundown of what appears to be happening:
- The test runner scans and discovers all 839 tests successfully (~31 seconds)
- "Run test started" is displayed
- Test discovery appears to happen again (?!), finding 0 tests for test executables, throwing timeout errors the whole way
- Part of the way through these failures, it begins to find the tests again
- It reports that it only found a subset of the tests
- It executes just this subset of the tests, requiring us to re-run "Not Run Tests"

Overall it took 2 minutes 26 seconds to scan our test executables, but it seems everything that needed discovered was done at 31 seconds.

We have "Parse Symbol Information", "Print debug info" and "Print test output" all set to "False"

The following is the raw output shown after cleaning my entire solution, then clicking "Run All" in Test Explorer.
I've removed the actual path/exe names and truncated repetitive lines:

```
------ Discover test started ------
Google Test Adapter: Test discovery starting...
Found 3 tests in executable C:\path\to\my.exe
Found 4 tests in executable C:\path\to\my.exe
Found 3 tests in executable C:\path\to\my.exe
Found 4 tests in executable C:\path\to\my.exe
Found 11 tests in executable C:\path\to\my.exe


(removed a bunch of similar lines for readability)


Found 4 tests in executable C:\path\to\my.exe
Found 34 tests in executable C:\path\to\my.exe
Found 9 tests in executable C:\path\to\my.exe
Found 2 tests in executable C:\path\to\my.exe
Found 1 tests in executable C:\path\to\my.exe
Test discovery completed, overall duration: 00:00:05.3113603
========== Discover test finished: 839 found (0:00:31.159) ==========
------ Run test started ------
Google Test Adapter: Test execution starting...
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
Found 0 tests in executable C:\path\to\my.exe
Found 0 tests in executable C:\path\to\my.exe
Found 0 tests in executable C:\path\to\my.exe


(removed a bunch of similar lines for readability)


ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
Found 0 tests in executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
Found 0 tests in executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
Found 0 tests in executable C:\path\to\my.exe
Found 9 tests in executable C:\path\to\my.exe
Found 1 tests in executable C:\path\to\my.exe


(removed a bunch of similar lines for readability)


Found 3 tests in executable C:\path\to\my.exe
Found 4 tests in executable C:\path\to\my.exe
Found 4 tests in executable C:\path\to\my.exe
Found 3 tests in executable C:\path\to\my.exe
Running 342 tests...
Google Test execution completed, overall duration: 00:02:06.1453077.
ERROR: 
================
The following errors and warnings occured during test execution (enable debug mode for more information):
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe


(removed a bunch of similar lines for readability)


ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
========== Run test finished: 342 run (0:02:26.653) ==========
```

**Comment by csoltenborn** [comment] 2018-01-19 17:38
The VS API for running tests (which is implemented by GTA and invoked by VS) has two methods: One receives executables, the other one receives test case objects (and is basically invoked through *Run selected tests*). In the former case, GTA has to perform test discovery again. The VS API is to blame here, so to say...

Here's some things I noticed:
* GTA itself performs test discovery within 5.3s (that log output is the very last thing GTA's according method does). The other 26s are on VS...
* The code executed when performing test discovery is the same for the actual discovery phase and the execution's discovery phase. However, it is invoked from different processes spawned by VS, which can cause differences between the two discoveries (see e.g. #168).

Despite that, here are some more questions the answers of which could be helpful: 
* What version of VS is this? 
* Are you using the old or new execution framework of GTA? 
* How does test discovery and execution of your test executables behave on the command line?
* Does the debug mode reveal any more information on the cause of the timeouts?

**Comment by loki980** [comment] 2018-01-19 18:22
Visual Studio 2015 Update 3
New text execution framework
Running a gtest executable with "--gtest_list_tests" on a single exe (we have 170some total) discovers 34 tests in 0.063 seconds.
Running the executable by itself completes in 1.543seconds - one of them takes 1.421 seconds, which is a performance test.

Debug mode is probably worth a separate comment...

**Comment by loki980** [comment] 2018-01-19 18:33
Is there somewhere I can send you this raw output?  It's a lot to summarize.  I don't necessarily want to post all the names of my tests here.

**Comment by csoltenborn** [comment] 2018-01-20 08:39
To be honest, I'd like to debug this openly such that others can learn from it, thus I would prefer if you post (i.e., attach as a file) the relevant lines (maybe use some regexes to get rid of your test names).

However, my impression is that there's something weird going on with your VS installation (do your coworkers also have that problem?), or that your test code has issues with the different execution environments (discovery and execution phase). I would try to figure out what your test code does when it does not return leading to the timeouts, e.g. by adding some debug output. Can you post the main method of one of the problematic executables? And, btw, is it always the same set of executables which timeouts, or does this differ?

**Comment by loki980** [comment] 2018-01-22 23:20
Yes, my coworkers have the issue.  We basically have the exact same setup.

I'm getting different results when I run without the new framework.  I'll post with an update in a bit.

[test scanning debug output.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/1653870/test.scanning.debug.output.txt)

**Comment by loki980** [comment] 2018-01-22 23:39
Here's the old framework.

[test scanning debug output old framework.txt](https://github.com/csoltenborn/GoogleTestAdapter/files/1653961/test.scanning.debug.output.old.framework.txt)

**Comment by csoltenborn** [comment] 2018-01-23 06:50
I had a brief look at your log files, but didn't notice anything particular... However, it appears that with the old execution framework, test discovery is much slower, but test execution (i.e., the discovery phase of executing your tests) works without problems?

Since the new execution framework is the default setting, and since I haven't yet heard of such problems, I still assume that this is not a general problem of that execution framework, but has to do with your specific tests. So, let's try figuring out what happens if GTA tries test discovery in the execution phase. Please answer my questions from my last comment and try to find out what's actually happening:
* In the case the set of problematic executables does not change, please post the main method of one of those
* Please try to add debug output to one of your problematic executables to find out whether it is executed at all (but hangs for some reason), how far execution goes and whether something particular prevents the executable from finishing execution
* One more question: Have you tried disabling parallel test execution?
* It could also be worth trying to raise the test discovery timeout to something insane (say, 5mins) just to figure out whether the executables just take quite a long time to finish

**Comment by loki980** [comment] 2018-01-23 20:18
Thanks for your comprehensive help.

> Can you post the main method of one of the problematic executables?

Sorry - this is a harder question to answer than it should be.  I *can*, but it's going to be confusing.  We use a framework on some tests that spawn threads for triggering external timeouts.  It's very complicated, uses testfixtures with SetUp() and TearDown() calls and are completely riddled with macros (I don't entirely like it since it's so confusing, but it was very difficult to get working.)  I'm not convinced it's a problem with these exes yet and don't want to sink a bunch of time into unwinding these function calls and macros unless it's absolutely necessary.
> And, btw, is it always the same set of executables which timeouts, or does this differ?

No - it isn't.  If I clean my solution, then click `Run All` in the Test Explorer window, the project builds and scans, discovering 843 tests.
> ========== Discover test finished: 843 found (0:00:26.052) ==========

 It then starts to run:
> ------ Run test started ------

This is followed by 14 seconds of 100% cpu usage on 1 core by the process vstest.executionengine.x86.exe

Then I see:
> Google Test Adapter: Test execution starting...

With debugging on, I get a bunch of:
> No settings configured for test executable 'C:\path\to\my.exe'; running with solution settings 

These messages keep appearing at the rate of one every half second or so, but no executables are spawned in devenv.exe while looking at Process Explorer.  Exactly 30 seconds later, in the same order the "No settings configured" messages are shown, I get the errors:
```
ERROR: Test discovery was cancelled after 30s for executable C:\path\to\my.exe
ERROR: Test whether the following commands can be executed sucessfully on the command line (make sure all required binaries are on the PATH):
cd "C:\path\to\"
my.exe --gtest_list_tests
Found 0 tests in executable C:\path\to\my.exe
```

Running the named executables with --gtest_list_tests instantly results in a list of the contained tests.

These messages continue, interleaved with the "No settings configured" messages until a certain point.  The failures are alphabetical, are not the same every time, and appear to be time-based.  The first time I ran it, the first 94 tests had the error.  Second time, 88 had the error.  Third time, 92.  (This is out of 176 total executables)  During this time, I saw only 1 of the executables spawned by devenv.exe in Process Explorer in probably 10 runs.

At some point, the errors stop and the remainder are discovered pretty much instantly.  I see devenv.exe spawn all the remaining executables, which run and close pretty much instantly:
```
Found 9 tests in executable C:\path\to\my.exe
Added testcase my.test1
Added testcase my.test2
Added testcase my.test3
Added testcase my.test4
```

Yes, the old framework doesn't throw errors and runs all the tests without the 30 second timeout issues.

Another note.  This seems to entirely stem from behavior caused by the `Run All` button.  I can click `Run All` and get the above to occur over and over again (30s timeouts, incomplete tests runs), beginning from:
> ------ Run test started ------

However, if I clean my solution, then build my solution, the same process as above occurs, but it stops at:
```
Test discovery completed, overall duration: 00:00:04.4975845
========== Discover test finished: 843 found (0:00:25.914) ==========
```

In the Tests Output window, I still see `No settings configured for test executable`, but everything is clean with no reported errors.

At this point, if I click `Run All` - the rescan occurs with the errors.  However, if I click `Run->Run Not Run Tests`, all 843 tests begin running immediately and complete as expected.

I have tried to disable parallel execution.  Same issues.

Going to try changing the timeout to 5 min.  Also, I'll try adding debug output to one of the alphabetically first executables that have the 30s timeout problem and post back.

**Comment by loki980** [comment] 2018-01-23 20:59
Ok - using the old test execution framework using `Run All`...

The solution builds, followed by a test scan.  However, this time the first scan takes significantly longer than 26 seconds:
```
No settings configured for test executable 'C:\path\to\my.exe'; running with solution settings: AdditionalTestExecutionParam: '', BatchForTestSetup: '', BatchForTestTeardown: '', BreakOnFailure: False, CatchExceptions: True, DebugMode: True, KillProcessesOnCancel: False, MaxNrOfThreads: 8, NrOfTestRepetitions: 1, ParallelTestExecution: False, ParseSymbolInformation: False, PathExtension: '', PrintTestOutput: False, RunDisabledTests: False, ShowReleaseNotes: True, ShuffleTests: False, ShuffleTestsSeed: 0, TestDiscoveryRegex: '\\test\\.*.\.exe', TestDiscoveryTimeoutInSeconds: 30, TestNameSeparator: '', TimestampOutput: False, TraitsRegexesAfter: {}, TraitsRegexesBefore: {}, UseNewTestExecutionFramework: False, WorkingDir: '$(ExecutableDir)'
Custom regex '\\test\\.*.\.exe' matches executable 'C:\path\to\my.exe'
Parsing pdb file "C:\path\to\my.pdb"
Found 9 test method symbols and 0 trait symbols in binary C:\path\to\my.exe
Added testcase my.test1
Added testcase my.test2
Added testcase my.test3
Added testcase my.test4
Found 4 tests in executable C:\path\to\my.exe

... repeated for each of 176 projects

Test discovery completed, overall duration: 00:02:03.6118236
========== Discover test finished: 843 found (0:02:25.299) ==========
------ Run test started ------
Visual Studio Version: VS2015
Google Test Adapter: Test execution starting...
```

It then proceeds to do the same thing.  `No settings configured for test executable` and `Parsing pdb file` with `Found` and `Added`.

After this second identical scan, it runs all tests successfully

**Comment by loki980** [comment] 2018-01-23 21:19
As a test, I wrote a quick script in python to see what discovery SHOULD take.

```
import fnmatch
import os

filecount = 0;

for root, dir, files in os.walk('.'):
    for filename in fnmatch.filter(files, '*.exe'):
          os.system(filename + " --gtest_list_tests")
```

Running `time python discoverTests.py` in my tests directory results in
```
real    0m7.456s
user    0m0.000s
sys     0m0.031s
```

**Comment by csoltenborn** [comment] 2018-01-24 11:02
Wow, lots of information :-)

Let's clarify a couple of things:
* VS test adapters implement two interfaces: One implementation is called at build completion time and performs test discovery; the passed executables are evaluated, and the test cases are reported to VS (which display them in the test explorer windows). The second implementation is called at test execution time and has two methods: One is passed a set of test executables to be run (and is called when *Run all* is selected), the other is passed test cases reused from discovery phase (and is called when tests are run e.g. through *Run selected tests* or *Run not run tests*). In the former case, we have to rescan the executables - this is by design of the VS test adapter API.
* During running a set of exectables, we run the same code as in the discovery phase. However, the code runs in a different process: The `vstest.executionengine.x86.exe` process runs execution code, and there should be a similar process for test discovery (these are spawned by VS).
* GTA allows to provide test settings on three different levels (VS options, solution, and project), which are then merged for a particular test executable. Thus, in debug mode we print the actual settings used for each executable to simplify debugging of configuration problems. The `No settings configured for test executable` message only refers to the fact that there are no dedicated settings for that particular executable, and that the solution settings are used instead.
* The difference between old and new execution framework is as follows: The VS test adapter API provides means to run an executable with a debugger attached. However, this does not allow access to the process' output. Therefore, when using the old execution framework, running and debugging tests differs slightly (e.g., test crash detection does not work), and it also allows to report test results to VS only when the execution has completed. Therefore, we run our own execution framework which uses VS API to attach the debugger if necessary, and allows accessing the output.

This should explain most of your questions. Since increasing discovery timeout "fixes" the situation, the executables are apparently indeed executed, but something takes a lot of time.

However, if your test executables' `main()` methods are that complicated, I would consider seeing this as a gtest smell. Afaik, the `main()` method of a gtest executable shall basically look like the following:

    int main(int argc, char **argv) {
        testing::InitGoogleTest(&argc, argv);
        return RUN_ALL_TESTS();
    }

All initialization logic should be executed at the according gtest hooks (initialization from the `main()` method probably going into [global test setup](https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md#global-set-up-and-tear-down)). This helps to make sure that during test discovery, only the according gtest code is executed. I would not be surprised if this would fix your test discovery issues...

It's still strange to see that stuff behave so differently - would love to know the cause... In fact, as soon as MS' and my repository are completely in sync, I hope to get the new execution framework reviewed by some MS guy.

**Comment by loki980** [comment] 2018-01-24 19:28
I've continued to try random things to try and shine some light on what's going on here.  For the 2nd test, alphabetically, I removed all dependencies on our custom framework and JUST had a test that looked like this:
```
/* Test Framework specific include files. */
#include <gtest/gtest.h>
TEST(my, test) {
  // Initial Startup, No Active or Enabled Alarms. 
  EXPECT_FALSE(0);
  EXPECT_TRUE(1);
}
int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```

That had the same exact 30second issue as the rest of them.  Does this mean that it's not our tests causing this?

I reverted this and tried something different.  I pared the 170some tests down to 16.  I no longer had the 30 second issue.  It identified 47 tests and ran them just fine.  I did, however, notice something that stood out.

**Comment by loki980** [comment] 2018-01-24 19:51
Ok, I stripped everything out.  There's no custom code and just 15 identical projects with 1 identical test in each of them.  I clean, then hit "Run All".  The 2 discovers are still done and the 1/2 second delay between `No settings configured` messages is still there.

**Comment by csoltenborn** [comment] 2018-01-25 05:41
* As I said, the "two discovers" are by design - no way around. 
* Test discovery is indeed performed in parallel (see [here](https://github.com/csoltenborn/GoogleTestAdapter/blob/f263d6e8724b839b0f3ff707055e936c12e7adde/GoogleTestAdapter/Core/GoogleTestDiscoverer.cs#L39)).
* Your stripped code could indeed imply that it's not related to your framework (it would still be possible that it causes problems if there are still things which get initialized, e.g. free, global variables). 
* I don't think that the `No settings configured` message is related to this - anyways, you can define project settings by providing a solution settings file, and by adding sections for the according projects (see docs). A .5s delay between those messages sounds reasonable to me since GTA scans each executable for the contained tests.

I'm currently a bit lost with your problem - please keep asking, but I'm not sure how I could help at this point...

**Comment by csoltenborn** [comment] 2018-01-26 08:49
Here's one thing I can do: I will give the old execution framework some love (hopefully at the weekend). In particular, test discovery is not yet performed in parallel with the old framework (I didn't bother to implement it since the old execution framework is to be removed at sme point in time anyways). This should speed up test discovery for you, and thus make GTA usable in your special case.

**Comment by csoltenborn** [comment] 2018-01-27 09:41
I have added support for parallel test discovery to the old execution framework (and fixed some minor bugs). Would you like to give [this version](https://ci.appveyor.com/project/csoltenborn/googletestadapter-u1cxh/branch/master/artifacts) a try?

**Comment by csoltenborn** [comment] 2018-02-05 06:14
Any news on this issue? I'd like to close it if your problems are solved (please share your solution to the problem if this is the case)...

**Comment by loki980** [comment] 2018-02-06 00:41
Sorry - was working on other stuff and dropped this.

Your version posted on Jan 27th makes discovery happen in 26 seconds, provided I don't use the "Run All" button.  That's good enough for me.  Thanks for your help.

**Comment by csoltenborn** [comment] 2018-02-06 05:06
You're welcome! I will then close this issue (and try to keep it in mind before removing the old execution framework :-) ).

**Closed by csoltenborn** 2018-02-06 05:06 UTC

**Comment by csoltenborn** [comment] 2018-02-10 08:43
This potentially blocks #106.
